kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
networking:
    ipFamily: ipv6
    apiServerAddress: 127.0.0.1
nodes:
- role: control-plane
  extraPortMappings:
  - containerPort: 80
    hostPort: 80
    listenAddress: "0.0.0.0" # Optional, defaults to "0.0.0.0"
- role: worker
  extraPortMappings:
      - containerPort: 80
        hostPort: 80
        listenAddress: "0.0.0.0" # Optional, defaults to "0.0.0.0"
